routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Redirect */
Route::get("/", function () {
    return redirect("lans");
})->name("home");

/** Sites */

/** Boxes */
Route::resource("boxes", "Box\BoxController", ["except" => ["show"]]);
Route::get("boxes/{box}/actions/{action}", "Box\BoxActionController@show")->name("boxes.actions.show");
Route::post("boxes/{box}/actions/{action}/execute", "Box\BoxActionController@execute")->name("boxes.actions.execute");

/** Box Services */
Route::get("boxes/{box}/services", "Box\BoxServiceController@index")->name("boxes.services.index");
Route::resource("boxservices", "Box\BoxServiceController", ["only" => ["store", "update", "destroy"]]);

/** Lans */
Route::resource("lans", "Lan\LanController", ["except" => ["show"]]);
Route::get("lans/{lan}/actions/{action}", "Lan\LanActionController@show")->name("lans.actions.show");
Route::post("lans/{lan}/actions/{action}/execute", "Lan\LanActionController@execute")->name("lans.actions.execute");

/** Services */
Route::resource("services", "Service\ServiceController", ["except" => ["show"]]);

/** Actions */
Route::resource("actions", "Action\ActionController", ["except" => ["show"]]);

/** Modules */




// BG: Added as stubs.
Route::resource("sites", "Site\SiteController", ["except" => ["show"]]);
Route::resource("actions", "Action\ActionController", ["except" => ["show"]]);
Route::resource("modules", "Module\ModuleController", ["except" => ["show"]]);

app/Http/Controllers/Action/ActionController.php
<?php

namespace App\Http\Controllers\Action;

use App\Action;
use App\Http\Formlets\Action\ActionForm;
use App\Http\Controllers\Controller;

class ActionController extends Controller
{

    public function index()
    {
        $actions = Action::all();

        return view('entities.action.index', [
            'actions' => $actions,
            "title" => "List of Actions"
        ]);
    }

    public function create(ActionForm $form)
    {
        return $form->renderWith([
            'route' => ['actions.store']
        ])->with([
            "title" => "Create Action form"
        ]);
    }

    public function edit(Action $action, ActionForm $form)
    {
        $form->setModel($action);
        $form->setFormView("entities.action.edit");

        return $form->renderWith([
            'route' => ['actions.update', $action],
            'method' => 'PATCH'
        ])->with([
            "title" => "Edit Action: $action->name",
            "action" => $action
        ]);
    }

    public function store(ActionForm $form)
    {
        $action = $form->store();
        flash("A new Action called $action->name has been created.");
        return redirect()->route('actions.index');
    }

    public function update(Action $action, ActionForm $form)
    {
        // Set correct Action to update
        $form->setModel($action);
        // Update Action
        $form->update();
        // notify
        flash("The Action $action->name has been updated.");
        // Redirect back to
        return redirect()->route('actions.edit', ['action' => $action]);
    }

    public function destroy(Action $action)
    {
        if ($action->active) {
            flash("You cannot delete and active action.")->error();
            return redirect()->route('actions.edit', $action);
        } else {
            Action::destroy($action->id);
            flash("The Action $action->name has been deleted.");
            return redirect()->route('actions.index');
        }
    }

}

resources/views/entities/action/partials/delete.blade.php
<form action="{{route('actions.destroy',$action)}}" method="POST">
    <input name="_token" type="hidden" value="{{csrf_token()}}"/>
    <button name="_method" class="btn btn-danger" value="delete">Delete Action</button>
</form>

resources/views/entities/action/partials/table.blade.php
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Class</th>
        <th>Scope</th>
        <th>Sig</th>
        <th>Seq</th>
        <th>Active</th>
        <th></th>
    </tr>
    @foreach($actions as $action)
        <tr class="table__row table__row-{{$action->activeClass()}}">
            <td>{{ $action->id }}</td>
            <td>{{ $action->name }}</td>
            <td>{{ $action->class }}</td>
            <td>{{ $action->scope }}</td>
            <td>{{ $action->sig }}</td>
            <td>{{ $action->seq }}</td>
            <td>{{ $action->active }}</td>
            <td class="text-right">
                <a class="btn btn-info" href="{{route('actions.edit', ['action'=> $action])}}">
                    edit
                </a>
            </td>
        </tr>
    @endforeach
</table>