routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Redirect */
Route::get("/", function () {
    return redirect("lans");
})->name("home");

/** Sites */

/** Boxes */
Route::resource("boxes", "Box\BoxController", ["except" => ["show"]]);
Route::get("boxes/{box}/actions/{action}", "Box\BoxActionController@show")->name("boxes.actions.show");
Route::post("boxes/{box}/actions/{action}/execute", "Box\BoxActionController@execute")->name("boxes.actions.execute");

/** Box Services */
Route::get("boxes/{box}/services", "Box\BoxServiceController@index")->name("boxes.services.index");
Route::resource("boxservices", "Box\BoxServiceController", ["only" => ["store", "update", "destroy"]]);

/** Lans */
Route::resource("lans", "Lan\LanController", ["except" => ["show"]]);
Route::get("lans/{lan}/actions/{action}", "Lan\LanActionController@show")->name("lans.actions.show");
Route::post("lans/{lan}/actions/{action}/execute", "Lan\LanActionController@execute")->name("lans.actions.execute");

/** Services */
Route::resource("services", "Service\ServiceController", ["except" => ["show"]]);

/** Actions */
Route::resource("actions", "Action\ActionController", ["except" => ["show"]]);

/** Modules */




// BG: Added as stubs.
Route::resource("sites", "Site\SiteController", ["except" => ["show"]]);
Route::resource("actions", "Action\ActionController", ["except" => ["show"]]);
Route::resource("modules", "Module\ModuleController", ["except" => ["show"]]);

app/Http/Controllers/Action/ActionController.php
<?php

namespace App\Http\Controllers\Action;

use App\Action;
use App\Http\Formlets\Action\ActionForm;
use App\Http\Controllers\Controller;

class ActionController extends Controller
{

    public function index()
    {
        $actions = Action::all();

        return view('entities.action.index', [
            'actions' => $actions,
            "title" => "List of Actions"
        ]);
    }

    public function create(ActionForm $form)
    {
        return $form->renderWith([
            'route' => ['actions.store']
        ])->with([
            "title" => "Create Action form"
        ]);
    }

    public function edit(Action $action, ActionForm $form)
    {
        $form->setModel($action);
        $form->setFormView("entities.action.edit");

        return $form->renderWith([
            'route' => ['actions.update', $action],
            'method' => 'PATCH'
        ])->with([
            "title" => "Edit Action: $action->name",
            "action" => $action
        ]);
    }

    public function store(ActionForm $form)
    {
        $action = $form->store();
        flash("A new Action called $action->name has been created.");
        return redirect()->route('actions.index');
    }

    public function update(Action $action, ActionForm $form)
    {
        // Set correct Action to update
        $form->setModel($action);
        // Update Action
        $form->update();
        // notify
        flash("The Action $action->name has been updated.");
        // Redirect back to
        return redirect()->route('actions.edit', ['action' => $action]);
    }

    public function destroy(Action $action)
    {
        if ($action->active) {
            flash("You cannot delete and active action.")->error();
            return redirect()->route('actions.edit', $action);
        } else {
            Action::destroy($action->id);
            flash("The Action $action->name has been deleted.");
            return redirect()->route('actions.index');
        }
    }

}

resources/views/entities/action/create.blade.php
@extends('layouts.main')

@section('actions')
    <a class="btn btn-info" href="{{route('actions.index')}}">
        All Actions
    </a>
@overwrite

@section('content')
    @nview('entities.action.forms.create')
@endsection

resources/views/entities/action/edit.blade.php
@extends('layouts.main')

@section('actions')
    <a class="btn btn-info" href="{{route('actions.index')}}">
        All Actions
    </a>
    @if(!$action->active)
        @include('entities.action.partials.delete')
    @endif
@overwrite

@section('content')
    @nview('entities.action.forms.edit')
@endsection

resources/views/entities/action/index.blade.php
@extends('layouts.main')

@section('actions')
    <a class="btn btn-info" href="{{route('actions.create')}}">
        Create new Action
    </a>
@overwrite

@section('content')
    @include('entities.action.partials.table')
@overwrite

resources/views/entities/action/show.blade.php
@extends('layouts.main')

@section('actions')
    <a class="btn btn-info" href="{{$backButton['route']}}">
        {{$backButton['text']}}
    </a>
@overwrite

@section('content')
    <p>{{$command}}</p>
    <p>{{$description}}</p>
    <form action=""></form>
    <form action="{{$executeButton['route']}}" method="POST">
        <input name="_token" type="hidden" value="{{csrf_token()}}"/>
        <button name="_method" class="btn btn-info" value="post">Do Action</button>
    </form>
    <hr>
    <h2>Action History</h2>
    <table class="table">
        <tr>
            <th>Event</th>
            <th>Status</th>
            <th>Message</th>
        </tr>
        @foreach($history as $itemAction)
            <tr class="table__item table__item-{{$itemAction->statusClass()}}">
                <td>{{$itemAction->event}}</td>
                <td>{{$itemAction->status}}</td>
                <td>{{$itemAction->message}}</td>
            </tr>
        @endforeach
    </table>
@overwrite